spring.application.name=ChefsMarker

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/chefs_marker
spring.datasource.username=root
spring.datasource.password=root


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# the above update operation syncs the entity changes to the db table (JPA does it). we don't have to query anything manually
spring.jpa.show-sql=true
#the above show-sql logs query operations